### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by dpoerschke** [HCL-TECH-SOFTWARE/Verse-Extension-Documentation#3]
Hi, there are dead links on the resources page: you can get there by clicking on the link https://doc.cwpcollaboration.com/verse-developer/ and then on the button "Go to new site" and then on the top right on "Resources":
https://opensource.hcltechsw.com/Verse-Extension-Documentation/docs/resources
All links listed under "Repositories" result in a 404 error.

On the getting started page there are dead links too: a click on "You can download the example directory ahead of time **here**" results in a 404: https://opensource.hcltechsw.com/Verse-Extension-Documentation/docs/getting-started

And another one: all links under "Prerequisites" (https://opensource.hcltechsw.com/Verse-Extension-Documentation/docs/development) are dead.

Sorry, but it is very frustrating to work with the verse documentation.

And unfortunately it is the same with the documentation on help.hcltechsw.com: If you try to change the version with the combo box in the upper right corner, you geht a 404 error for every version newer than 1.0.7. 
https://help.hcltechsw.com/verse_onprem/1.0.7/admin/topics/verse_extensions.html

**Comment by hcl-bpchasse** [comment]
@dpoerschke Can you please test the links again to see if they are working for you now? Please let me know whether or not they are working for you now. Thanks!

**Comment by doug-macdonald1** [comment]
The folder structure for the documentation on help.hcltechsw.com has changed since 1.0.7. For example, 
https://help.hcltechsw.com/verse_onprem/1.0.7/admin/topics/verse_extensions.html
https://help.hcltechsw.com/verse_onprem/1.0.8/admin/verse_extensions.html

**Comment by dpoerschke** [comment]
@hcl-bpchasse Links are working now - thanks! :-)

**Comment by hcl-bpchasse** [comment]
@dpoerschke Thank you for confirming that the links are working for you. I will now close this issue. Thanks again!
